- name: kill selenium-server
  shell: "kill -9 `cat tmp/pids/puma.pid` && rm tmp/pids/puma.pid"
  ignore_errors: yes
  args:
    chdir: "{{ app_dir }}"

- name: selenium-server daemon
  shell: "nohup java -jar selenium-server-standalone-3.9.1.jar &"
  args:
    chdir: "{{ app_dir }}"

- name: Php artisan serve
  shell: php artisan serve --host=0.0.0.0
  args:
    chdir: /vagrant/xpacy